#!/usr/bin/env bash

#	Update and install nala:
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install -y nala
# Update with nala:
sudo nala update && sudo nala upgrade -y
#	Purge any docker packages from ubuntu install:
sudo apt remove $(dpkg --get-selections docker.io docker-compose docker-compose-v2 docker-doc podman-docker containerd runc | cut -f1)
#	Add repos and install basic utilities:
sudo add-apt-repository ppa:zhangsongcui3371/fastfetch
sudo nala update
sudo nala install -y fastfetch sl wget
#	Add Docker's official GPG key:
sudo nala install -y curl ca-certificates
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
#	Add docker repository to apt sources:
sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF
sudo nala update
#	Install the Docker packages:
sudo nala install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
# Enable docekr service:
sudo systemctl start docker
# Add user to docker group:
sudo usermod -aG docker $USER