#!/usr/bin/env bash

# Update and install nala:
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install -y nala
# Update and upgrade the system:
sudo nala update && sudo nala upgrade -y
# Purge old docker packages:
sudo apt remove $(dpkg --get-selections docker.io docker-compose docker-doc podman-docker containerd runc | cut -f1)
#	Install docker engine:
sudo nala install -y curl wget sl ca-certificates fastfetch
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
# Add docker repository to apt:
sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/debian
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF
#	Install docker packages:
sudo nala update
sudo nala install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
# Enable docker service:
sudo systemctl enable --now docker
# Add user to docker group:
sudo usermod -aG docker $USER
