#!/bin/bash

# Sanity check:
echo "Would you like to install docker? (y/n)"
read dockerInstall

if [[ ${dockerInstall,,} == "y" ]]; then
  hostOS=$(hostnamectl | grep -i operating)
  read -ra distro <<< $hostOS
  case "${distro[2]}" in
    Debian)
      # Debian:
      ./docekr-debian
      ;;
    Ubuntu)
      # Ubuntu:
      ./docker-ubuntu
      ;;
    Fedora)
      # Fedora:
      ./docker-fedora
      ;;
    Rocky|Red)
      # RHEL:
      ./docker-rhel
      ;;
    *)
      # Other:
      echo "Other Linux distros are not supported at this time. 
      Please try this script again while using a supported platform."
      sleep 5
      clear
      exit 1
  esac
else
    echo "Very well - Return and run this script again when you are ready to begin the installation."
    sleep 5
    exit 1
fi
# Portainer install prompt:
clear
echo "Would you like to install portainer? (y/n)"
read portainerInstall
if [[ ${portainerInstall,,} == "y" ]]; then
  echo "Which version of portainer would you like to install:
  1 - Portainer Business Edition
  2 - Portainer Community Edition
  3 - Portainer Agent"
  read portainerVersion
  echo "Very well."
  case $portainerVersion in
    1)
      # Install portainer ee docker container:
      ./portainer-ee
      ;;
    2)
      # Install portainer server docker container:
      ./portainer-ce
      ;;
    3)
      # Install portainer agent docker container:
      ./portainer-agent
      ;;
  esac
else
  # Future install instructions:
  echo "Very well, portainer will NOT be installed now."
  sleep 1
  echo "If you would like to install portainer in the future, return to this directory and run the script for the version you would like to install."
  sleep 2
fi
#	Clear before ending:
clear
echo "Installation complete."
